version: '3.8'

networks:
  quiz-dev:
    driver: bridge

services:
  app:
    container_name: quiz
    build: .
    depends_on:
      - database
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Server=database,1433;Database=DataStoreDB;User Id=sa;Password=Fast192837465;TrustServerCertificate=True
      - Redis__ConnectionString=redis:6379
    ports:
      - "8080:80"
      - "8443:5001"
    networks:
      - quiz-dev

  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Fast192837465"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - quiz-dev
    volumes:
      - sqlserverdata:/var/opt/mssql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - quiz-dev

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - quiz-dev

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - quiz-dev

volumes:
  sqlserverdata:
